name: Mirror to Gitopia

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Gitopia
        run: | 
          curl https://get.gitopia.com | bash
      - name: Get Gitopia Repo
        run: |
          git remote add MIM gitopia://gitopia1h5r4fg3jgy8hu3tn7hk5dyhes305u9874pfv66/MIM
      - name: Get Gitopia Repo
        run: |
          git push gitopia ${GITHUB_REF}:${{inputs.branch}} --force
      - env:
        GITOPIA_WALLET: ${{ secrets.GITOPIA_WALLET }}
